md Ayuda2
cd C:\Ayuda2
md C:\Ayuda2\SOM C:\Ayuda2\FOL C:\Ayuda2\MME C:\Ayuda2\AAI\WORD C:\Ayuda2\AAI\EXCEL C:\Ayuda2\RL\WINDOWS C:\Ayuda2\RL\LINUX\GRAFICO C:\Ayuda2\RL\LINUX\COMANDO C:\Ayuda2\RL\SHELL\BASICO C:\Ayuda2\RL\SHELL\AVANZADO
cd RL\LINUX\COMANDO
MD ..\..\SHELL\AVANZADO\PROGRAMAS ..\..\..\AAI\EXCEL\FACTURAS\ENERO 
cd ..\..\..
MOVE RL AAI\REDES
cd SOM
tree ..\AAI > ..\FOL\Arbol1.txt
copy ..\FOL\Arbol1.txt ..\MME\Arbol2.txt
type ..\MME\ARBOL2.TXT
ECHO SHELL ES UN LENGUAJE DE PROGRAMACION > ..\AAI\WORD\DATOS1.TXT
ECHO BAJO EL SISTEMA OPERATIVO LINUX > ..\AAI\WORD\DATOS2.TXT
ECHO POTENTE SISTEMA >> ..\AAI\WORD\DATOS1.TXT
ECHO FACIL DE MANEJAR >> ..\AAI\WORD\DATOS1.TXT
DIR ..\AAI
RD ..\AAI\EXCEL /S
DEL ..\MME\ARBOL2.TXT
COPY ..\AAI\WORD\DATOS1.TXT + ..\AAI\WORD\DATOS2.TXT ..\AAI\WORD\COMPLETO.TXT
HELP ATTRIB
HELP FC > COMANDO.TXT
REN COMANDO.TXT COMANDOFC.TXT
DIR ..\AAI\WORD\D*
DIR ..\?O*